### ISSUE TITLE
First dev/build fails on changeset permissions

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-frameworktest#28]
> [Emergency] Uncaught LogicException: The current member does not have permission to publish this ChangeSet.

**Comment by tractorcow** [comment]
hmmm I see. =(

**Comment by tractorcow** [comment]
Should we make ChangeSet::publish() not fail on invalid permission? canPublish() still has the logic, but user code is able to conditionally omit the check if it invokes ->publish() directly.

**Comment by tractorcow** [comment]
I've created https://github.com/silverstripe/silverstripe-framework/pull/6498, so we can use the actAs() method to bump permissions for certain actions.
