### ISSUE TITLE
Ability to generate [x] random page types

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-frameworktest#41]
This will help testing the overhead associated with site tree generation, i.e. `/admin/pages/treeview` referenced here: https://github.com/silverstripe/silverstripe-cms/issues/1977

One good approach would be to have a separate task to create randomly named page type files (within a range) and then integrate that into [FTPageMakerTask](https://github.com/silverstripe/silverstripe-frameworktest/blob/master/code/tasks/FTPageMakerTask.php#L36) to utilize either `Page` or any of the randomized page types (which will not vary from `Page` except in name). With this in mind, it may be best to ensure that the randomly generated page extend a single specific page class which can be used to then determine which (of the random set of pages) to create in this `FTPageMakerTask` (to ensure we don't randomly create instances of pages that are built separately for unrelated testing purposes).

**Comment by unclecheese** [comment]
@patricknelson Want to have a look? https://github.com/silverstripe/silverstripe-frameworktest/pull/45
