### ISSUE TITLE
When adding a new item on gridfield I get an error

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-frameworktest#8]
I'm on feature-test-pages/gridfield/ (GridFieldTestPage) and I click the 'Add Company' button and get this error:

[User Error] Uncaught Exception: Object->__call(): the method 'push' does not exist on 'HTMLText'

Trace
Object->__call(push,Array) 
GridFieldDetailForm.php:625
HTMLText->push(ArrayData) 
GridFieldDetailForm.php:625
GridFieldDetailForm_ItemRequest->Breadcrumbs() 
GridFieldDetailForm.php:363
GridFieldDetailForm_ItemRequest->ItemEditForm(GridField,SS_HTTPRequest) 
GridFieldDetailForm.php:291
GridFieldDetailForm_ItemRequest->edit(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,edit) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
GridFieldDetailForm.php:93

Is there something wrong with the core gridfield code or is the this function which I think is creating the new company?

Company.php (line 83)
public function requireDefaultRecords() {
        parent::requireDefaultRecords();
        $companySet = DataObject::get('Company');
        foreach ($companySet as $company) {
            $company->delete();
        }

```
    foreach($this->data() as $companyData){
        $company = new Company();
        $company->Name = $companyData[0];
        $company->Category = $companyData[1];
        $company->Revenue = $companyData[2];
        $company->CEO = $companyData[3];
        $company->write();
    }
    DB::alteration_message("Added default records to Company table","created");
}
```

**Comment by dhensby** [comment]
4 years old, I assume this is no longer a problem
